SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;
-------INNER JOIN
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPT.DEPTNO FROM EMP ,DEPT  WHERE EMP.DEPTNO =DEPT.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPT.DEPTNO FROM EMP ,DEPT  WHERE DEPT.DEPTNO =EMP.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E,DEPT D WHERE E.DEPTNO =D.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E,DEPT D WHERE D.DEPTNO =E.DEPTNO ORDER BY DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP ,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO ORDER BY DEPT.DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP ,DEPT WHERE DEPT.DEPTNO=EMP.DEPTNO ORDER BY DEPT.DEPTNO;
SELECT E.*,D.* FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO ORDER BY E.DEPTNO;
SELECT E.*,D.* FROM EMP E,DEPT D WHERE D.DEPTNO=E.DEPTNO ORDER BY E.DEPTNO;
SELECT EMPNO,ENAME,JOB,SAL,E.DEPTNO,DNAME,LOC,GRADE FROM EMP E,DEPT D,SALGRADE S WHERE E.DEPTNO =D.DEPTNO AND SAL>=700 AND SAL<=9000 ORDER BY GRADE;
SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC, GRADE FROM EMP E, DEPT D, SALGRADE S WHERE E.DEPTNO=D.DEPTNO AND E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND DNAME IN('RESEARCH','SALES') AND SAL BETWEEN 1000 AND 2500 ORDER BY E.DEPTNO;
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, E.DEPTNO, DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND HIREDATE LIKE '%81' AND COMM IS NULL AND MGR IS NOT NULL AND E.DEPTNO IN(20, 30) ORDER BY SAL DESC;
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, SAL*12 AS ANNSAL, COMM, E.DEPTNO, DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND LOC IN('DALLAS','CHICAGO') AND SAL*12 BETWEEN 18000 AND 36000 AND COMM IS NULL ORDER BY ANNSAL;

------LEFT JOIN
SELECT EMPNO, ENAME, JOB, SAL, D.DEPTNO, DNAME, LOC FROM EMP E LEFT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPT.DEPTNO FROM EMP LEFT OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E LEFT OUTER JOIN DEPT D ON E.DEPTNO =D.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E LEFT OUTER JOIN DEPT D ON D.DEPTNO =E.DEPTNO ORDER BY DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP LEFT OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO ORDER BY DEPT.DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP ,DEPT WHERE DEPT.DEPTNO=EMP.DEPTNO(+) ORDER BY DEPT.DEPTNO;
SELECT E.*,D.* FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO(+) ORDER BY E.DEPTNO;
SELECT E.*,D.* FROM EMP E,DEPT D WHERE D.DEPTNO=E.DEPTNO(+) ORDER BY E.DEPTNO;
SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE FROM EMP E LEFT OUTER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT E.EMPNO,E.ENAME,E.SAL,D.DNAME,S.GRADE FROM EMP E LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO LEFT JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC, GRADE FROM EMP E LEFT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO LEFT OUTER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

-----RIGHT OUTER JOIN

SELECT EMPNO, ENAME, JOB, SAL, D.DEPTNO, DNAME, LOC FROM EMP E RIGHT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPT.DEPTNO FROM EMP RIGHT OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E RIGHT OUTER JOIN DEPT D ON E.DEPTNO =D.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E RIGHT OUTER JOIN DEPT D ON D.DEPTNO =E.DEPTNO ORDER BY DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP RIGHT OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO ORDER BY DEPT.DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP ,DEPT WHERE DEPT.DEPTNO(+)=EMP.DEPTNO ORDER BY DEPT.DEPTNO;
SELECT E.*,D.* FROM EMP E,DEPT D WHERE E.DEPTNO(+)=D.DEPTNO ORDER BY E.DEPTNO;
SELECT E.*,D.* FROM EMP E,DEPT D WHERE D.DEPTNO(+)=E.DEPTNO ORDER BY E.DEPTNO;
SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE FROM EMP E RIGHT OUTER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT E.EMPNO,E.ENAME,E.SAL,D.DNAME,S.GRADE FROM EMP E RIGHT JOIN DEPT D ON E.DEPTNO = D.DEPTNO RIGHT JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC, GRADE FROM EMP E RIGHT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO RIGHT OUTER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

------FULL OUTER JOIN

SELECT EMPNO, ENAME, JOB, SAL, D.DEPTNO, DNAME, LOC FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPT.DEPTNO FROM EMP FULL OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO =D.DEPTNO ORDER BY DEPTNO;
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,D.DEPTNO FROM EMP E FULL OUTER JOIN DEPT D ON D.DEPTNO =E.DEPTNO ORDER BY DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP FULL OUTER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO ORDER BY DEPT.DEPTNO;
SELECT EMP.*,DEPT.DEPTNO,DNAME,LOC FROM EMP FULL OUTER JOIN DEPT ON DEPT.DEPTNO=EMP.DEPTNO ORDER BY DEPT.DEPTNO;
SELECT E.*,D.* FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO ORDER BY E.DEPTNO;
SELECT E.*,D.* FROM EMP E FULL OUTER JOIN DEPT D ON D.DEPTNO=E.DEPTNO ORDER BY E.DEPTNO;
SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE FROM EMP E FULL OUTER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT E.EMPNO,E.ENAME,E.SAL,D.DNAME,S.GRADE FROM EMP E FULL JOIN DEPT D ON E.DEPTNO = D.DEPTNO FULL JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC, GRADE FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO FULL OUTER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
